name: web_response_cache
description: A Flutter package offering multiple ways to cache responses obtained from web requests.
version: 0.0.4
repository: https://github.com/Schloool/web-response-cache-flutter

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
